OBJS_TEST_CAUSALIZE := $(OBJS_COMMON) \
            util/debug.o \
            causalize/cycles_identification_strategy.o \
            test/causalize/cycles_identification_strategy_test.o

LIB_TEST = -lboost_unit_test_framework

test/causalize/cycles_identification_strategy_test: $(OBJS_TEST_CAUSALIZE)
	$(CXX) $(CXXFLAGS) -o test/causalize/cycles_identification_strategy_test $(OBJS_TEST_CAUSALIZE) $(LIB_TEST)



	
