OBJS_MMO := $(OBJS_COMMON) \
            mmo/main.o \
            mmo/traverse_example.o \
            mmo/mmo_class.o \
            util/ast_util.o \
            util/type.o \
            util/symbol_table.o \
            util/type_check.o \
            mmo/tomicro.o \
            causalize/find_state.o 
      

mmo/mmo: $(OBJS_MMO)
	$(CXX) $(CXXFLAGS) -o mmo/mmo $(OBJS_MMO)



	
