OBJS_MMO := $(OBJS_COMMON) \
            mmo/main.o \
            mmo/mmo_class.o \
            util/ast_util.o \
            util/type.o \
            util/symbol_table.o \
            util/type_check.o \
            mmo/tomicro.o \
            causalize/state_variables_finder.o 
      

bin/mmo: $(OBJS_MMO)
	$(CXX) $(CXXFLAGS) -o bin/mmo $(OBJS_MMO)



	
