OBJS_CAUSALIZE := $(OBJS_COMMON) \
            mmo/mmo_class.o \
            util/ast_util.o \
            util/type.o \
            util/type_check.o \
            util/symbol_table.o \
            causalize/main.o \
            causalize/find_state.o

causalize/causalize: $(OBJS_CAUSALIZE)
	$(CXX) $(CXXFLAGS) -o causalize/causalize $(OBJS_CAUSALIZE)



	
