OBJS_ANTIALIAS := $(OBJS_COMMON) \
            mmo/mmo_class.o \
            util/ast_util.o \
            util/type.o \
            util/debug.o \
            util/type_check.o \
            util/symbol_table.o \
            antialias/remove_alias.o \
            causalize/state_variables_finder.o \
            causalize/compref_occurrence.o \
            antialias/main.o 

bin/antialias: $(OBJS_ANTIALIAS)
	$(CXX) $(CXXFLAGS) -o bin/antialias $(OBJS_ANTIALIAS)



	
